"""empty message

Revision ID: 202cafbcd36e
Revises: dc0859fbe51d
Create Date: 2019-07-19 16:19:44.652408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202cafbcd36e'
down_revision = 'dc0859fbe51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eggsales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('requested', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('bank', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('pen_allocation', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eggsales')
    # ### end Alembic commands ###
