"""empty message

Revision ID: 42b374b15921
Revises: 202cafbcd36e
Create Date: 2019-07-20 23:51:39.977418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b374b15921'
down_revision = '202cafbcd36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eggsales', sa.Column('issued', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eggsales', 'issued')
    # ### end Alembic commands ###
