"""empty message

Revision ID: 7f00a119938e
Revises: 42b374b15921
Create Date: 2019-07-30 09:37:20.781636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f00a119938e'
down_revision = '42b374b15921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('croptypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=20), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('croptypes')
    # ### end Alembic commands ###
