"""empty message

Revision ID: 892dcbebc283
Revises: c432fd50d038
Create Date: 2019-06-11 17:36:23.478471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892dcbebc283'
down_revision = 'c432fd50d038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivables', sa.Column('v_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receivables', 'v_price')
    # ### end Alembic commands ###
