"""empty message

Revision ID: 9658abd54b82
Revises: f48be77cc29c
Create Date: 2019-07-18 19:48:10.018867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9658abd54b82'
down_revision = 'f48be77cc29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('supply_id', sa.Integer(), nullable=True))
    op.add_column('eggsupplies', sa.Column('supply_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eggsupplies', 'supply_id')
    op.drop_column('allocations', 'supply_id')
    # ### end Alembic commands ###
