"""empty message

Revision ID: dc0859fbe51d
Revises: f497cb00a890
Create Date: 2019-07-19 09:26:51.423029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc0859fbe51d'
down_revision = 'f497cb00a890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eggsupplies', 'o_bal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eggsupplies', sa.Column('o_bal', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
